### ISSUE TITLE
Truncated collapsible region after resize the page

### ISSUE THREAD

**Issue by nmouillet** [eberhardt/moodle-filter_collapsible#2]
When you load a page in full screen, then you resize the page to be smaller and finally you un-collapse a field, the text is truncated (see image below)
![collapsible](https://cloud.githubusercontent.com/assets/6358307/10186773/f7678cea-6753-11e5-820c-d3ad7d6480a9.PNG)
I've not found the JS, maybe it's a bug in bootstrap and not in the filter (I use Clean theme on Moodle 2.9.2+). Anyway, i've put this code in my CSS as a workaround:
div.collapsibleregion.collapsablefiltered:not(.collapsed) {
    height: auto!important;
}

**Comment by eberhardt** [comment]
I don't create the JS for that plugin. It's all core code. I suggest to report that in the Moodle bug tracker or (since I personally don't believe, that they'll fix it) change this in your own themes. You can also create a local plugin, which has two files in it: A `style.css` and a `version.php`. The style must contain your code and the version must be like other `version.php` (just lookup other plugins).

Personally I don't want to force any formating by a plugin (which is by `!important`) since it could interfere with other themes.

**Comment by nmouillet** [comment]
You're right, it's not a filter-related problem.
